### ISSUE TITLE
Yarn build error 'ERR_OSSL_EVP_UNSUPPORTED'

### ISSUE THREAD

**Issue by wallywhatever** [simap/Firestorm#39]
Yarn build fails. 
EDIT: using `$ export NODE_OPTIONS=--openssl-legacy-provider` works as a temporary fix

The following is the stdout:

```
yarn build
yarn run v1.22.19
$ react-scripts build
Creating an optimized production build...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/home/servo/Firestorm/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/servo/Firestorm/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/servo/Firestorm/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/servo/Firestorm/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/servo/Firestorm/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/servo/Firestorm/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/servo/Firestorm/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/servo/Firestorm/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/home/servo/Firestorm/node_modules/react-scripts/scripts/build.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/home/servo/Firestorm/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/servo/Firestorm/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/servo/Firestorm/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/servo/Firestorm/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/servo/Firestorm/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/servo/Firestorm/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/servo/Firestorm/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/servo/Firestorm/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v19.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by caleyg** [comment]
I'm late to the game here, but could you try using `node 16.x` instead of your installed version of `node 19.x`?
